### ISSUE TITLE
Requirements txt error

### ISSUE THREAD

**Issue by furkanarius** [mediacloud/feed_seeker#1]
Hi,

When I try to install the package, this is the error message I receive. 

`Collecting feed_seeker
  Using cached https://files.pythonhosted.org/packages/fa/5e/ec1666a581b15829bbf2d4f83013e47f8ad89d99de82f905c73f13befe15/feed_seeker-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5w/s8hbw79j3vqc5cj4bg_gw7bh0000gn/T/pip-install-282Sdn/feed-seeker/setup.py", line 13, in <module>
        with open(requirements_file) as f:
      File "/Users/furkan/latestPY/lib/python2.7/codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/private/var/folders/5w/s8hbw79j3vqc5cj4bg_gw7bh0000gn/T/pip-install-282Sdn/feed-seeker/requirements.txt'`
    
    ----------------------------------------
`Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5w/s8hbw79j3vqc5cj4bg_gw7bh0000gn/T/pip-install-282Sdn/feed-seeker/`

**Comment by pypt** [comment]
Hi, could you please try installing this with Python 3.5+?

**Comment by furkanarius** [comment]
Working now. Thanks! I didn't realize it was Python 3+

**Comment by pypt** [comment]
Thanks for the report, it's our bad. Stated the required Python version explicitly in 
f745ea3, will release at some point in the future.
